apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp
    type: fornt-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
        type: fornt-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
