apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: my-app
    type: fornt-end
spec:
  selector:
    matchLabels:
      name: my-app
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        name: my-app
    spec:
      containers:
        - name: nginx
          image: nginx
